# Documentations
# https://io-wiki.mercator-ocean.fr/public/software/howtos/automated-check-and-format
# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"
